### ISSUE TITLE
[RFC] Is there a need for Hypertext Application Languages?

### ISSUE THREAD

**Issue by HTMLGhozt** [nwthomas/lambda-school-alumni-tips#17]
I've accumulated some resources which don't really fit anywhere, the best I could come up with to eschew the Addendum tag is [Hypertext Application Languages (HALs)](https://en.wikipedia.org/wiki/Hypertext_Application_Language):

- [JSON Schema](http://json-schema.org/) - Home of the JSON working draft
- [JSON-LD (Linking Data)](https://json-ld.org/) - A super-set of JSON that integrates connected data
- [Open Graph protocol](http://ogp.me/) - Adds additional metadata which enables any web page to become a rich object in a social graph

**Comment by nwthomas** [comment]
I like it. Do you want to submit a PR for these?

**Comment by HTMLGhozt** [comment]
There's some argument that this could probably be a subset of [HTTP Calls and Requests](https://github.com/nwthomas/lambda-school-alumni-tips/blame/master/tips/technology-resources.md#L131).

**Comment by HTMLGhozt** [comment]
Closed by #18. If it's decided that this could be a subset of HTTP Calls and Requests. that could be done at a later time.
