### ISSUE TITLE
.vscode folder

### ISSUE THREAD

**Issue by HTMLGhozt** [nwthomas/lambda-school-alumni-tips#22]
Do we really need the .vscode settings folder? It seems like this is unneeded, but if you have a reason for it then this issue can at least provide a searchable reason.

**Comment by nwthomas** [comment]
Excellent point - I forgot to include it in a .gitignore, and use header color-coding locally to quickly differentiate my projects from each other (or a back-end from a front-end) while working. Thanks Thomas!

I'll remove it later this afternoon.

**Comment by nwthomas** [comment]
Fixed in 3889b827fe418285bd92663f6f3c12622aaf85b7
