### ISSUE TITLE
[RFC] Should there be a spot or tag to include paid courses?

### ISSUE THREAD

**Issue by HTMLGhozt** [nwthomas/lambda-school-alumni-tips#8]
While most things for programming can be found for free in some form it's the unfortunate truth that the most concise, focused, and up to date information is sometimes behind a paywall.

Here's some examples for consideration:

- [TylerMcGinnis.com](https://tylermcginnis.com/) - bar none the best place to learn React/React Native beyond what Lambda School teaches.
- [TestingJavaScript.com](https://testingjavascript.com/) - probably the best information I have seen about testing period and it focuses specifically on JavaScript.
- [Refactoring UI](https://refactoringui.com/book/) - One of the best books I've read on how to refactor mediocre UI/UX.

### Less-focused Considerations:
- [egghead.io](https://egghead.io/) - General content focused on JavaScript and the surrounding ecosystem.
- [Frontend Masters](https://frontendmasters.com/) - Specifically focused on the frontend ecosystem
- [PluralSight](https://www.pluralsight.com/) - What it lacks for in quality it makes up for in breadth of content. It easily outclasses the other two for the amount of categories, but it doesn't have the same pedigree of teachers - that's not saying there's not great teachers, but rather there's some not so great teachers on the platform.
- [Treehouse](https://teamtreehouse.com/) - Where many of the above resources fall short is that it's mainly watch and do on your own. Treehouse changes that by providing a much more integrated and diverse experience breaking down between watching and writing code.

**Comment by nwthomas** [comment]
Moving this improvement point off this thread to Trello
